### ISSUE TITLE
watchdog thread dies under load when pis is stopped

### ISSUE THREAD

**Issue by m4r10k** [n0r1sk/smsgateway#21]
Didn't checked the list. I must figure out what happend here.

2015-09-17 16:57:03,982 [wis:DEBUG]  ROUTERDB: Read routing entries
2015-09-17 16:57:03,983 [wis:DEBUG]  ROUTERDB: 3 routing entries selected.
2015-09-17 16:57:03,983 [wis:DEBUG]  ROUTERDB: Read routing entries
2015-09-17 16:57:03,983 [wis:DEBUG]  ROUTERDB: 1 routing entries selected.
2015-09-17 16:57:03,983 [wis:DEBUG]  WATCHDOG: process with route [] 
2015-09-17 16:57:03,984 [wis:DEBUG]  WATCHDOG:  Sending to PIS
2015-09-17 16:57:03,986 [wis:DEBUG]  STDIO: Exception in thread Watchdog:
2015-09-17 16:57:03,986 [wis:DEBUG]  STDIO: Traceback (most recent call last):
2015-09-17 16:57:03,986 [wis:DEBUG]  STDIO:   File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
2015-09-17 16:57:03,987 [wis:DEBUG]  STDIO:     self.run()
2015-09-17 16:57:03,987 [wis:DEBUG]  STDIO:   File "/opt/smsgateway/wis/application/watchdog.py", line 210, in run
2015-09-17 16:57:03,987 [wis:DEBUG]  STDIO:     self.process()
2015-09-17 16:57:03,987 [wis:DEBUG]  STDIO:   File "/opt/smsgateway/wis/application/watchdog.py", line 196, in process
2015-09-17 16:57:03,987 [wis:DEBUG]  STDIO:     self.send(sms, route)
2015-09-17 16:57:03,988 [wis:DEBUG]  STDIO:   File "/opt/smsgateway/wis/application/watchdog.py", line 47, in send
2015-09-17 16:57:03,988 [wis:DEBUG]  STDIO:     route[0]["pisurl"] +
2015-09-17 16:57:03,988 [wis:DEBUG]  STDIO: IndexError: list index out of range
2015-09-17 16:57:03,988 [wis:DEBUG]  STDIO: 
2015-09-17 16:57:13,315 [wis:DEBUG]  ROUTER: Finishing router run
2015-09-17 16:57:13,315 [wis:DEBUG]  ROUTER: Starting router run
2015-09-17 16:57:13,315 [wis:DEBUG]  ROUTER: Starting raise obsolet

**Comment by m4r10k** [comment]
Damn! It happened what I though in #18 . The watchdog is broken when one of the pid modems is switched from one wis to another.
