### ISSUE TITLE
add python inspect information on stderr stdout logging to filelogger

### ISSUE THREAD

**Issue by m4r10k** [n0r1sk/smsgateway#22]
would be nice to track the calling class, method or function

**Comment by m4r10k** [comment]
2015-09-17 21:07:59,573 [wis:DEBUG]  STDIO: Exception in thread Router:
2015-09-17 21:07:59,573 [wis:DEBUG]  STDIO: Traceback (most recent call last):
2015-09-17 21:07:59,573 [wis:DEBUG]  STDIO:   File "/usr/lib/python3.2/threading.py", line 740, in _bootstrap_inner
2015-09-17 21:07:59,574 [wis:DEBUG]  STDIO:     self.run()
2015-09-17 21:07:59,574 [wis:DEBUG]  STDIO:   File "/opt/smsgateway/wis/application/router.py", line 60, in run
2015-09-17 21:07:59,574 [wis:DEBUG]  STDIO:     Helper.receiverouting()
2015-09-17 21:07:59,574 [wis:DEBUG]  STDIO:   File "/opt/smsgateway/wis/application/helper.py", line 253, in receiverouting
2015-09-17 21:07:59,574 [wis:DEBUG]  STDIO:     f = urllib.request.urlopen(request, data, timeout=5)
2015-09-17 21:07:59,574 [wis:DEBUG]  STDIO:   File "/usr/lib/python3.2/urllib/request.py", line 139, in urlopen
2015-09-17 21:07:59,574 [wis:DEBUG]  STDIO:     return opener.open(url, data, timeout)
2015-09-17 21:07:59,574 [wis:DEBUG]  STDIO:   File "/usr/lib/python3.2/urllib/request.py", line 370, in open
2015-09-17 21:07:59,575 [wis:DEBUG]  STDIO:     response = self._open(req, data)
2015-09-17 21:07:59,575 [wis:DEBUG]  STDIO:   File "/usr/lib/python3.2/urllib/request.py", line 388, in _open
2015-09-17 21:07:59,575 [wis:DEBUG]  STDIO:     '_open', req)
2015-09-17 21:07:59,575 [wis:DEBUG]  STDIO:   File "/usr/lib/python3.2/urllib/request.py", line 348, in _call_chain
2015-09-17 21:07:59,575 [wis:DEBUG]  STDIO:     result = func(*args)
2015-09-17 21:07:59,575 [wis:DEBUG]  STDIO:   File "/usr/lib/python3.2/urllib/request.py", line 1160, in http_open
2015-09-17 21:07:59,575 [wis:DEBUG]  STDIO:     return self.do_open(http.client.HTTPConnection, req)
2015-09-17 21:07:59,575 [wis:DEBUG]  STDIO:   File "/usr/lib/python3.2/urllib/request.py", line 1145, in do_open
2015-09-17 21:07:59,576 [wis:DEBUG]  STDIO:     r = h.getresponse()
2015-09-17 21:07:59,576 [wis:DEBUG]  STDIO:   File "/usr/lib/python3.2/http/client.py", line 1052, in getresponse
2015-09-17 21:07:59,576 [wis:DEBUG]  STDIO:     response.begin()
2015-09-17 21:07:59,576 [wis:DEBUG]  STDIO:   File "/usr/lib/python3.2/http/client.py", line 346, in begin
2015-09-17 21:07:59,576 [wis:DEBUG]  STDIO:     version, status, reason = self._read_status()
2015-09-17 21:07:59,576 [wis:DEBUG]  STDIO:   File "/usr/lib/python3.2/http/client.py", line 308, in _read_status
2015-09-17 21:07:59,576 [wis:DEBUG]  STDIO:     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
2015-09-17 21:07:59,576 [wis:DEBUG]  STDIO:   File "/usr/lib/python3.2/socket.py", line 287, in readinto
2015-09-17 21:07:59,576 [wis:DEBUG]  STDIO:     return self._sock.recv_into(b)
2015-09-17 21:07:59,577 [wis:DEBUG]  STDIO: socket.error: [Errno 104] Connection reset by peer
2015-09-17 21:07:59,577 [wis:DEBUG]  STDIO:
