### ISSUE TITLE
Error in smstransfer class

### ISSUE THREAD

**Issue by m4r10k** [n0r1sk/smsgateway#35]
JSON dumps exception

015-09-23 10:15:31,054 [wis:DEBUG]  STDIO: Called from: _bootstrap_inner
2015-09-23 10:15:31,054 [wis:DEBUG]  STDIO: Exception in thread Watchdog:
2015-09-23 10:15:31,054 [wis:DEBUG]  STDIO: Traceback (most recent call last):
2015-09-23 10:15:31,055 [wis:DEBUG]  STDIO:   File "/usr/lib/python3.2/threading.py", line 740, in _bootstrap_inner
2015-09-23 10:15:31,055 [wis:DEBUG]  STDIO:     self.run()
2015-09-23 10:15:31,055 [wis:DEBUG]  STDIO:   File "/opt/smsgateway/wis/application/watchdog.py", line 212, in run
2015-09-23 10:15:31,055 [wis:DEBUG]  STDIO:     self.process()
2015-09-23 10:15:31,055 [wis:DEBUG]  STDIO:   File "/opt/smsgateway/wis/application/watchdog.py", line 186, in process
2015-09-23 10:15:31,055 [wis:DEBUG]  STDIO:     self.deligate(smstrans, route)
2015-09-23 10:15:31,056 [wis:DEBUG]  STDIO:   File "/opt/smsgateway/wis/application/watchdog.py", line 95, in deligate
2015-09-23 10:15:31,056 [wis:DEBUG]  STDIO:     jdata = smstrans.getjson()
2015-09-23 10:15:31,056 [wis:DEBUG]  STDIO:   File "/opt/smsgateway/wis/application/smstransfer.py", line 94, in getjson
2015-09-23 10:15:31,057 [wis:DEBUG]  STDIO:     return json.dumps(self.smstransfer)
2015-09-23 10:15:31,057 [wis:DEBUG]  STDIO:   File "/usr/lib/python3.2/json/__init__.py", line 226, in dumps
2015-09-23 10:15:31,058 [wis:DEBUG]  STDIO:     return _default_encoder.encode(obj)
2015-09-23 10:15:31,058 [wis:DEBUG]  STDIO:   File "/usr/lib/python3.2/json/encoder.py", line 187, in encode
2015-09-23 10:15:31,058 [wis:DEBUG]  STDIO:     chunks = self.iterencode(o, _one_shot=True)
2015-09-23 10:15:31,058 [wis:DEBUG]  STDIO:   File "/usr/lib/python3.2/json/encoder.py", line 245, in iterencode
2015-09-23 10:15:31,058 [wis:DEBUG]  STDIO:     return _iterencode(o, 0)
2015-09-23 10:15:31,058 [wis:DEBUG]  STDIO:   File "/usr/lib/python3.2/json/encoder.py", line 169, in default
2015-09-23 10:15:31,058 [wis:DEBUG]  STDIO:     raise TypeError(repr(o) + " is not JSON serializable")
2015-09-23 10:15:31,059 [wis:DEBUG]  STDIO: TypeError: datetime.datetime(2015, 9, 23, 8, 15, 30, 981286) is not JSON serializable

**Comment by m4r10k** [comment]
Closed because it is not possible to reproduce it
