### ISSUE TITLE
validate regular expression if it is compileable

### ISSUE THREAD

**Issue by m4r10k** [n0r1sk/smsgateway#47]

**Comment by neuholdm** [comment]
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python3.2/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/usr/local/lib/python3.2/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/opt/smsgateway/wis/wis.py", line 408, in sendsms
    Helper.processsms(sms)
  File "/opt/smsgateway/wis/application/helper.py", line 54, in processsms
    match = re.search(route["regex"], sms.smsdict["targetnr"])
  File "/usr/lib/python3.2/re.py", line 161, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.2/re.py", line 263, in _compile
    return _compile_typed(type(pattern), pattern, flags)
  File "/usr/lib/python3.2/functools.py", line 184, in wrapper
    result = user_function(_args, *_kwds)
  File "/usr/lib/python3.2/re.py", line 275, in _compile_typed
    return sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.2/sre_compile.py", line 491, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.2/sre_parse.py", line 692, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib/python3.2/sre_parse.py", line 315, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python3.2/sre_parse.py", line 640, in _parse
    p = _parse_sub(source, state)
  File "/usr/lib/python3.2/sre_parse.py", line 315, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python3.2/sre_parse.py", line 520, in _parse
    raise error("nothing to repeat")
sre_constants.error: nothing to repeat

**Comment by m4r10k** [comment]
Fixed in v1.3
